---
title: "Computational Research Data Management"
format: 
  html:
    toc: false
date-modified: last-modified
date-format: long
date: 2023-11-30
bibliography: resources/references.bib
summary: Index page, intro to course
#https://emojidb.org/quarto-emojis for emojis copypaste
---

<!--
# Put above to hide navigation (left), toc (right) or footer (bottom)
# You should hide the navigation if there are no subsections
# You should hide the Table of Contents if there are no important titles
-->

## Research Data Management for NGS data 
The course "Research Data Management (RDM) for Next Generation Sequencing (NGS) data" is designed to provide participants with foundational knowledge and practical skills in handling the extensive data generated by modern NGS studies. It emphasizes the importance of Open Science and FAIR principles in managing NGS data effectively. This course covers essential principal and best practices guidelines in data organization, metadata annotation, version control, and data preservation. These principles are explored from a computational perspective, ensuring participants gain hands-on experience in applying them to real-world scenarios in their research labs. Additionally, the course delves into FAIR principles and Open Science, promoting collaboration and reproducibility in research endeavors. By the course's conclusion, attendees will possess essential tools and techniques to address the data challenges prevalent in today's NGS research landscape.

:::{.callout-note title="Course Overview"}
- 📖 **Syllabus:**

1. Data Lifecycle Management 
2. Data Management Plans (DMPs)
3. Data Organization and Documentation 
4. Metadata standards and data description
5. Version Control and Collaboration
6. Reproducible Research Practices and Data analysis
7. Data sharing and data preservation

- ⏰ **Total Time Estimation:** X hours  
- 📁 **Supporting Materials:**  
- 👨‍💻 **Target Audience:** PhD, MsC, anyone interested in RDM for NGS data.
- 👩‍🎓 **Level:** Beginner.
- 🔒 **License:** [Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) license.](https://creativecommons.org/licenses/by-sa/4.0/legalcode)  
- 💰 **Funding:** This project was funded by the Novo Nordisk Fonden (NNF20OC0063268).
:::

<!--     
    1. Research Data Management: definition and importance (1)
    2. NGS data
    3. Data Life Cycle (1)
    4. Open Science and FAIR principles (1)
    5. Data Management planning (2)
    6. Folder and file structures applied to NGS data (3)
    7. Metadata applied to NGS data (4)
    8. Database creation (data and projects) (4)
    9. Version control of your data analysis (5)
    10. Archiving and repositories (7)
--> 

:::{.callout-warning title="Course Requirements"}
- Basic understanding Next Generation Sequencing data and formats.
- Command Line experience
- Basic programming experience
- Quarto or Mkdocs tools
:::

This course offers participants with an in-depth introduction to effectively managing the vast amounts of data generated in modern studies. Throughout the program, emphasis is placed on practical understanding of RDM principles and the importance of efficient handling of large datasets. In this context, participants will learn the necessity of adopting Open Science and FAIR principles for enhancing data accessibility and reusability.

Participants will acquire practical skills for organizing data, including the creation of folder and file structures, and the implementation of metadata to facilitate data discoverability and interpretation. Special attention is given to the development of Data Management Plans (DMPs) with examples tailored to omics data, ensuring compliance with institutional and funding agency requirements while maintaining data integrity. Attendees will also gain insights into the establishment of simple databases and the use of version control systems to track changes in data analysis, thereby promoting collaboration and reproducibility.

The course concludes with a focus on archiving and data repositories, enabling participants to learn strategies for preserving and sharing data for long-term scientific usage. By the end of the course, attendees will be equipped with essential tools and techniques to effectively navigate the challenges prevalent in today's research landscape. This will not only foster successful data management practices but also enhance collaboration within the scientific community.

::: {.callout-tip title="Course Goals"}
By the end of this workshop, you should be able to apply the following concepts in the context of Next Generation Sequencing data:

- Understand the Importance of Research Data Management (RDM)
- Familiarize Yourself with FAIR and Open Science Principles
- Draft a Data Management Plan for your own Data
- Establish File and Folder Naming Conventions
- Enhance Data with Descriptive Metadata
- Implement Version Control for Data Analysis
- Select an Appropriate Repository for Data Archiving
- Make your data analysis and workflows reproducible and FAIR
:::

:::{.callout-warning}
This is a computational workshop that focuses primarily on the digital aspect of our data. While wet lab Research Data Management (RDM) involving protocols, instruments, reagents, ELM or LIMS systems is integral to the entire RDM process, it won't be covered in this course.

As part of effective data management, it's crucial to prioritize strategies that ensure security and privacy. While these aspects are important, please note that they won't be covered in our course. However, we highly recommend enrolling in the [GDPR course](https://heads.ku.dk/course/gdpr_workshop/) offered by Center for Health Data Science, specially if you're working with sensitive data. This course specifically focuses on GDPR compliance and will provide you with valuable insights and skills in managing data privacy and security.

:::

#### Danish institutional RDM links 

- [University of Copenhagen](https://kunet.ku.dk/work-areas/research/data/Pages/default.aspx)
- [University Library of Southern Denmark](https://sdunet.dk/en/research/research-data-management-support)
- [Technical University of Denmark](https://www.bibliotek.dtu.dk/en/publishing/research-data)
- [Aalborg University](https://www.researcher.aau.dk/guides/research-data/data-management)
- [Aarhus University](https://medarbejdere.au.dk/en/research-data-management)

#### Acknowledgements

- [RDMkit](https://rdmkit.elixir-europe.org/index), ELIXIR (2021) Research Data Management Kit. A deliverable from the EU-funded ELIXIR-CONVERGE project (grant agreement 871075).
- University of Copenhagen Research Data Management Team.
- Martin Proks and Sarah Lundregan, Brickman Lab, NNF Center for Stem Cell Biology (reNEW), University of Copenhagen.
- [Richard Dennis](https://data-champions.renew-platforms.dk/), Data Steward, NNF Center for Stem Cell Biology (reNEW), University of Copenhagen.
- [NBISweden](https://uppsala.instructure.com/courses/48087/pages/introduction-to-data-management-practices).

<!-- 
### Feedback form

We would greatly appreciate to know your thoughts about this workshop. Please, follow this [link](https://forms.office.com/e/BZkpzDKL0L) to answer 9 fast questions!
-->
